### ISSUE TITLE
Native image, -Dquarkus.native.debug.enabled=true, Quarkus 1.8+ does not copy sources; Quarkus 1.7.x does

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#145]
Hello,

With Oracle GraalVM 20.2+ or Mandrel 20.1+ as JAVA_HOME and GRAALVM_HOME, bin/ on PATH, the following should generate sources alongside debuginfo: 

```
cd /tmp
curl -O -J  https://code.quarkus.io/api/download
unzip code-with-quarkus.zip
cd code-with-quarkus/
./mvnw package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=registry.redhat.io/quarkus/mandrel-20-rhel8 -Dquarkus.native.debug.enabled=true
``` 

There is neither `/tmp/code-with-quarkus/target/sources-cache` nor `/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/sources/`.

If you simply change the version in `pom.xml` to 1.7.5.Final and re-run exactly the same `./mvnw` command above, you get populated `/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/sources/`.

**Comment by zakkak** [comment]
@Karm the problem you describe has been fixed by:

1. https://github.com/quarkusio/quarkus/pull/12294 (fixes the issue with sources not being generated when building with a container)
2. https://github.com/quarkusio/quarkus/pull/12351 (places source cache to `/tmp/code-with-quarkus/target/sources`)

There is also 3. https://github.com/quarkusio/quarkus/pull/12405 that removes the need to point gdb to `sources/src` in addition to `sources`.

Now from these three PRs only 1. has been backported to Quarkus 1.7 (1.7.4.Final to be precise) so that's why with 1.7.5 you get the sources in `/tmp/code-with-quarkus/target/code-with-quarkus-1.0.0-SNAPSHOT-native-image-source-jar/sources/` but not in 1.8.
All three (1. 2. and 3.) will be available in the upcoming Quarkus 1.9.0 release.

**Comment by Karm** [comment]
@zakkak Thanks for the summary. It makes sense now.

**Comment by zakkak** [comment]
@Karm can we close this since it is Quarkus issue and not a Mandrel/Graal issue?

**Comment by Karm** [comment]
Closing.
