### ISSUE TITLE
[Documentation] How Does Mandrel Differ From Graal - could a table be added?

### ISSUE THREAD

**Issue by rubyFeedback** [graalvm/mandrel#343]
Right now the main README explains "How Does Mandrel Differ From Graal".

Would it be possible to add a table showing the main differences?

Specifically I just learned about mandrel, and read the subsection but I am still
not sure whether I need it or whether mandrel may be useful.

Would it be possible for some of you folks to perhaps add a short table that
summarizes the main differences via a quick-to-look at table?

For instance, I would also like to know what advantages mandrel brings,
in particular when it comes to speed. Any benchmark would be nice, but
it need not be a benchmark we can reproduce, it is fine if the table would
say "+5% faster in some benchmarks" or something like that, just so that
we have a ROUGH estimate when we ask "why use mandrel"?. Thank you
for reading this issue request.

**Comment by jerboaa** [comment]
I'm not sure such a table would make a lot of sense as it's a moving target. It's specifically a distro of GraalVM which removes some (not needed) features. The [readme section](https://github.com/graalvm/mandrel#how-does-mandrel-differ-from-graal) pretty much sums it up.

The main purpose of mandrel can be summarized as: Provide a native-image binary for use of Quarkus apps[1]. In the Quarkus context it should be a drop-in replacement for GraalVM's native-image generator. Nothing more, nothing less. It's also a trimmed down native-image distro of GraalVM which works with plain OpenJDK (instead of needing LabsOpenJDK which has a bit more patches than plain OpenJDK). There are no intentions to diverge from upstream in any other regard. In particular, there shouldn't be any significant difference wrt benchmarks. We'd be contributing improvements to upstream GraalVM should we notice any.

So if you're interested in GraalVM because of its native-image capability it might be something for you. Otherwise it likely isn't. Note that mandrel is mostly tested in the Quarkus context. I.e. used for generating native-images for Quarkus apps.

Hope this helps.

[1] https://developers.redhat.com/blog/2021/04/14/mandrel-a-specialized-distribution-of-graalvm-for-quarkus
