### ISSUE TITLE
Mandrel releases naming

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#41]
Graal CE releases are available in https://github.com/graalvm/graalvm-ce-builds/releases and use the following naming convention:

graalvm-ce-java`java major version`-`os`-`arch`-`graal version`.tar.gz

## Facts

* Mandrel doesn't need to follow a similar convention
* Mandrel is being built using upstream OpenJDK instead of labs-OpenJDK
* Mandrel (like Graal) is sensitive to OpenJDK changes (thus its builds are tightly coupled to the OpenJDK version)

## Proposal A
mandrel-java`java major version`-`os`-`arch`-`mandrel version`.tar.gz

e.g. mandrel-java11-linux-amd64-20.1.3.2.tar.gz (see #39 for versioning)

## Proposal B
mandrel-`os`-`arch`-`mandrel version`.tar.gz

e.g. mandrel-linux-amd64-20.1.3.2.tar.gz (see #39 for versioning)

If Mandrel is going to support only java 11 for the foreseeable feature there is no need to add `java11` in the releases.

## Proposal C
mandrel-java`java major.minor.patch.build version`-`os`-`arch`-`mandrel version`.tar.gz

e.g. mandrel-java11.0.8.4-linux-amd64-20.1.3.2.tar.gz (see #39 for versioning)

Since Mandrel is tightly coupled to OpenJDK we might want to make the OpenJDK version visible in the releases. Keep in mind though that this info can be easily obtained by running `java --version` or `native-image --version` after extracting the tarball. I find this naming of great value if we plan to release tarballs containing only the Mandrel bits so that users could untar them and install alongside an existing OpenJDK installation.

**Comment by Karm** [comment]
My take on this issue:

## Proposal A :heavy_check_mark: 
I am fine with this. `mandrel version` should be made of the closest GraalVM version plus our qualifier at the end, e.g. Mandrel 20.1.0.2 would be GraalVM 2.1.0 plus some changes.

## Proposal B :x: 
I would favor the others over this one. Graal delivers JDK 8 and 11 and I think Mandrel has to make it clear that it is Java 11 only we are delivering.

## Proposal C :heavy_check_mark: 
I like this one too.  Instead of `mandrel-java11.0.8.4-linux-amd64-20.1.3.2.tar.gz` I would set `mandrel-jdk11.0.8.4-linux-amd64-20.1.3.2.tar.gz`. The exact version is shown on the AdoptOpenJDK site too: 

![adoptopenjdk](https://user-images.githubusercontent.com/691097/84365686-1a3e6500-abd2-11ea-8c9c-5f5a155610bd.png)

**Comment by galderz** [comment]
Proposal A
========

Fine by me.

Proposal B
========
Problem: Java 11 is not the only thing in the foreseeable future. We know Java 17 will be an LTS to be released in 2021 and I'm sure we'll support both Java 11 and 17 then, and for a while after that.

Proposal C
========
This only makes sense to me if we're planning to take given x.y.z Mandrel version and we expect to release it with different Java minor and/or micro versions, e.g.

* mandrel-java11.0.8.4-linux-amd64-20.1.3.2.tar.gz
* mandrel-java11.0.7.4-linux-amd64-20.1.3.2.tar.gz

Do we really see that happening? If not I'd go with proposal A.

**Comment by maxandersen** [comment]
Proposal A - assuming that mandrel version at the end is graalvm version it is based on or how ?

Proposal B is just a no go.

Proposal C I still don't get the value for users.

**Comment by zakkak** [comment]
> Proposal A - assuming that mandrel version at the end is graalvm version it is based on or how ?

The mandrel version in the end will be the one decided in #39

**Comment by zakkak** [comment]
Proposal C seems to be controversial and its verbosity is not needed at this point.
As a result, mandrel releases are expected to be named like `mandrel-java11-linux-amd64-20.1.3.2.Final.tar.gz` (i.e. Proposal A)
