### ISSUE TITLE
Mandrel distro doesn't offer org.graalvm.nativeimage, unable to use FFM API 

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#753]
As I am switching IDE from  Mandrel-24.2.0-dev6eefc9c7aae9 (build 24-beta+3-ea) to GraalVM CE 24-dev+1.1 (build 24+1-jvmci-b01) I noticed that I cannot import  e.g.
```
import org.graalvm.nativeimage.hosted.Feature;
import org.graalvm.nativeimage.hosted.RuntimeForeignAccess;
```
as we don't seem to package `org.graalvm.nativeimage` :thinking:

**Comment by jerboaa** [comment]
@Karm Please provide more details on this. To me this seems intentional. What do you need `org.graalvm.nativeimage.hosted.Feature` for? It's internal API that we should not use. We are trying hard to only use `org.graalvm.sdk:nativeimage` artefact in Quarkus as that's the public API.

Also, the claim of not packaging `org.graalvm.nativeimage` seems wrong as it's in the `nativeimage.jar`:
```
$ jar -tf mandrel-build/lib/jvmci/nativeimage.jar | grep RuntimeForeignAccess
org/graalvm/nativeimage/impl/RuntimeForeignAccessSupport.class
org/graalvm/nativeimage/hosted/RuntimeForeignAccess.class
```

**Comment by Karm** [comment]
@jerboaa I might be just fighting IDEA the wrong way. I will compare why it works with GraalVM CE for me, drop caches and report back...

**Comment by zakkak** [comment]
Did you try rerunning:

```
mx --primary-suite=substratevm -y intellijinit
```

?
